tilte: Pontes
remote_theme: "pages-themes/minimal@v0.4.0"
theme: jekyll-theme-minimal

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      theme: "jekyll-theme-minimal"

defaults:
  -
    scope:
      path: "_pages"
    values:
      layout: "default"
      theme: "jekyll-theme-cayman"
